---
title: "Physics Validation of Y3 Clusters Code"
author: "Y3 Cluster Team"
date: "12/12/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      fig.align = "center")
library(tidyverse)
```

## Introduction

This document presents analysis to demonstrate the calculations done by the Y3 clusters analysis code.

Our unit tests require fractional errors to be less than one part per million,
unless otherwise indicated.

## Omega_z

```{r, include = FALSE}
omega_z <- read_tsv("../data/omega_z_sdss.out")
omega_z <- mutate(omega_z, resid = ytrue - ytest)
```

### Absolute comparison of omega_z

```{r fig.cap = "Absolute comparision"}
ggplot(omega_z) +
  geom_point(aes(x = z, y = ytrue), color = "red", shape = 1) +
  geom_point(aes(x = z, y = ytest), color = "blue", shape = 3) +
  xlab("redshift") +
  ylab("survey area")  
```

### Relative error

```{r figcap = "Relative comparison"}
ggplot(omega_z, aes(x = z, y = resid/ytrue)) +
  geom_point() +
  xlab("redshift") +
  ylab("relative difference in survey area") 
```

## Session information

```{r echo = TRUE}
sessionInfo()
```

