[runtime]
sampler = test
root = ${COSMOSIS_SRC_DIR}

[DEFAULT]
fatal_errors = T
CSL = ${COSMOSIS_STANDARD_LIBRARY}

[test]
save_dir = simple_gpu_output

[pipeline]
#modules = consistency camb sigma_r mf_tinker deltasigma numberCountsSimple
modules = consistency camb sigma_r mf_tinker numberCountsSimple
values = ${Y3_CLUSTER_CPP_DIR}/cosmosis_tests/values/values_buzzard.ini
likelihoods =
extra_output =
quiet = F
debug = T
timing = T

[consistency]
file = %(CSL)s/utility/consistency/consistency_interface.py

[camb]
file = %(CSL)s/boltzmann/camb/camb_interface.py
mode = all
lmax = 2500
feedback = 0
zmin = 0.0
zmax = 1.0
nz = 100
kmin = 1e-4
kmax = 50.0
nk = 500
halofit_version = takahashi
nonlinear = pk

[sigma_r]
file = %(CSL)s/boltzmann/sigmar/sigmar.py
matter_power = matter_power_lin
zmin = 0.0
zmax = 1.0
dz = 0.1
rmin = 1.0
rmax = 50.0
dr = 5.0

[mf_tinker]
file = %(CSL)s/mass_function/mf_tinker/tinker_mf_module.so
redshift_zero = 0
feedback = 0

[deltasigma]
file = ${Y3_CLUSTER_CPP_DIR}/src/modules/deltasigma/deltasigma.py
R_perp_min = 0.01
R_perp_max = 250
R_perp_bins = 1000
Radii_min = 0.01
Radii_max = 1000
Radii_bins = 1000
M_min = 1E12
M_max = 1E16
M_bins = 100

[numberCountsSimple]
file = ${Y3_CLUSTER_CPP_DIR}/release-build/src/modules/simple_gpu/numberCountsSimple.so
lo_low = 10.0
lo_high = 200.0
zt_low = 0.1
zt_high = 0.5
lnm_low = 31.0
lnm_high = 36.0
zo_low = 0.2 0.35
zo_high = 0.35 0.5
eps_rel = 1e-3
eps_abs = 1e-10
max_eval = 1.0e6
algorithm = pagani
use_cartesian_product = true
