; Parameters and data in CosmoSIS are organized into sections
; so we can easily see what they mean.
; There is only one section in this case, called cosmological_parameters
; omega_m and sigma8_input are from DES Y1 data
[cosmological_parameters]
omega_m  =  0.264
h0  =  0.7  
omega_b = 0.047
tau = 0.08
n_s = 0.96
A_s = 2.1565e-09
sigma8_input = 0.807 
omega_k = 0.0
w = -1.0
wa = 0.0

[cluster_abundance]
hmf_s = 4.50732047e-02
hmf_q = 1.01958078e+00
