[runtime]
; The test sampler just runs a single parameter set
sampler = test
root = ${COSMOSIS_SRC_DIR}

[DEFAULT]
fatal_errors=T

[test]
save_dir = compton_y_sims_output

[output]
filename = randomized_starts_out_08_1000.txt
format = text
verbosity = 0

[pipeline]
modules = consistency camb sigma_r growth mf_tinker tinker_bias cluster_sz compton_y_sims cluster_sz_like
values = ${Y3_CLUSTER_CPP_DIR}/cosmosis_tests/compton_y_sims_values.ini
likelihoods = compton_y_sims
extra_output = 
quiet=T
debug=T
timing=T

; The consistency module translates between our chosen parameterization
; and any other that modules in the pipeline may want (e.g. camb)
[consistency]
file = cosmosis-standard-library/utility/consistency/consistency_interface.py

[camb]
file = cosmosis-standard-library/boltzmann/camb/camb.so
mode=all
lmax=2500
feedback=0
zmin = 0.0
zmax = 0.55
nz = 100
; kmin = 1e-4
; kmax = 50.0
; nk = 1000
matter_power_lin_version = 3

[sigma_r]
file = cosmosis-standard-library/boltzmann/sigmar/sigmar.py
zmin = 0.0
zmax = 1.0
dz = 0.05
rmin = 1.0
rmax = 50.0
dr = 1.0
matter_power = "matter_power_lin"

[growth]
file = cosmosis-standard-library/structure/growth_factor/interface.so
zmin = 0.0
zmax = 1.0
dz = 0.05

[mf_tinker]
file = cosmosis-standard-library/mass_function/mf_tinker/tinker_mf_module.so
redshift_zero = 0
feedback = 0

[tinker_bias]
file = ${Y3_CLUSTER_CPP_DIR}/tinker_bias/tinker_bias.py

[cluster_sz]
file = cosmosis-standard-library/cluster-sz/cluster_sz.py
profiletype = battaglia
;; Arcminutes
thetas = 0.128400 0.211700 0.349030 0.575460 0.948770 1.564300 2.579000 4.252100 7.010500 11.558000 19.056999 31.419001 51.800999 85.405998 140.809998 232.160004 382.760010 631.070007
;; Gaussian PSF, 1 std in arcmin
; This is SPT (FWHM = 1 arcmin)
;sigma_psf = 0.4247
; This is Planck (FWHM = 10 arcmin)
sigma_psf = 4.247
;; Solar masses
Mmin = 2e14
Mmax = 1e+15
nM = 6
zmin = 0.225
zmax = 0.375
nz = 4

[compton_y_sims]
file = ${Y3_CLUSTER_WORK_DIR}/src/modules/compton_y_sims.so
thetas = 0.128400 0.211700 0.349030 0.575460 0.948770 1.564300 2.579000 4.252100 7.010500 11.558000 19.056999 31.419001 51.800999 85.405998 140.809998 232.160004 382.760010 631.070007
;;  I would like to do this... a lot simpler
; M_low = 2e+14 5e+14 8e+14
; M_high = 5e+14 8e+14 1e+15
; z_low = 0.2 0.25 0.3 0.35
; z_high = 0.25 0.3 0.35 0.4
M_low = 2e+14 5e+14 8e+14 2e+14 5e+14 8e+14 2e+14 5e+14 8e+14 2e+14 5e+14 8e+14
M_high = 5e+14 8e+14 1e+15 5e+14 8e+14 1e+15 5e+14 8e+14 1e+15 5e+14 8e+14 1e+15
z_low = 0.2 0.2 0.2 0.25 0.25 0.25 0.3 0.3 0.3 0.35 0.35 0.35
z_high = 0.25 0.25 0.25 0.3 0.3 0.3 0.35 0.35 0.35 0.4 0.4 0.4

eps_rel = 1e-3
eps_abs = 1e-15
max_eval = 10000

[cluster_sz_like]
file = ${Y3_CLUSTER_CPP_DIR}/cosmosis_tests/compton_y_sims_like.py
data_dir = ${Y3_CLUSTER_CPP_DIR}/data/sz_sims/
;; Tells the likelihood to ignore the highest-angle y-value in the data vector.
;; This is because the cluster_sz module has trouble computing the 2-halo at high angle
;; TODO FIXME: see above two lines
;; To stop this behavior, set this to 0
ignore_last = 1
;; This is copied here because the likelihood module _cannot_ read from
;; `compton_y_sims`. so for now we are just duplicating
M_low = 2e+14 5e+14 8e+14 2e+14 5e+14 8e+14 2e+14 5e+14 8e+14 2e+14 5e+14 8e+14
M_high = 5e+14 8e+14 1e+15 5e+14 8e+14 1e+15 5e+14 8e+14 1e+15 5e+14 8e+14 1e+15
z_low = 0.2 0.2 0.2 0.25 0.25 0.25 0.3 0.3 0.3 0.35 0.35 0.35
z_high = 0.25 0.25 0.25 0.3 0.3 0.3 0.35 0.35 0.35 0.4 0.4 0.4
