[runtime]
; The test sampler just runs a single parameter set
sampler = test
root = ${PWD}

[DEFAULT]
lo_bins = 20.0 27.9 37.6 50.3 69.3 110.0
zo_bins = 0.1 0.3
radii_bins = 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0

[test]
; These are the parameters for this sampler.
; In this case there is just one parameter
save_dir = mass_concentration_test_output

; If something goes wrong this will aid diagnosis
fatal_errors=T

[output]
filename = cross_output.txt
format = text
verbosity= 0

; The pipeline section contains information
; that describes the sequence of calculations
; to be done and what we want out at the end
[pipeline]
; The list of modules to be run, in this order.
; The modules named here must appear as sections below
modules = consistency camb 
; The file to get cosmological and nuisance parameters
; from.
values = ${Y3_CLUSTER_CPP_DIR}/cosmosis_tests/values/values_comp.ini
; Not used here, becuase we are not sampling
likelihoods = 
extra_output = 
quiet=F
debug=T
timing=F

; The consistency module translates between our chosen parameterization
; and any other that modules in the pipeline may want (e.g. camb)
[consistency]
file = ${COSMOSIS_STANDARD_LIBRARY}/utility/consistency/consistency_interface.py

[camb]
file = ${COSMOSIS_STANDARD_LIBRARY}/boltzmann/camb/camb_interface.py
mode=power
power_spectra=delta_tot delta_nonu
lmax=2500
feedback=2
zmin = 0.0
zmax = 0.55
nz = 100
kmin = 1e-3
kmax = 10.0
nk = 1000
# these are required for the masses_test.ini, to match the mass function produced, and correction in mf_tinker_test.py
neutrino_hierarchy = inverted
num_massive_neutrinos = 3

[mf_tinker]
file = ${COSMOSIS_STANDARD_LIBRARY}/mass_function/mf_tinker/tinker_mf_module.so
# seems not to have any effect
;matter_power_lin_section_name = "matter_power_lin_cdm_baryon"  
# this is used by mf_tinker, 2 is choosing "matter_power_lin_cdm_baryon" = delta_nonnu
# this is used by mf_tinker, 2 is choosing "cdm_baryon_power" = delta_nonnu   (understanding as of Aug 2022)
matter_power_lin_version = 2  
redshift_zero = 0
feedback=0

[mf_tinker_test]
file = ${Y3_CLUSTER_CPP_DIR}/cosmosis_tests/mf_tinker_test.py

