;; This CosmoSIS file is intended to replicate results from Matteo Costanzi,
;; purely for validation/sanity check purposes

[runtime]
sampler = test
root = ${COSMOSIS_SRC_DIR}

[test]
save_dir = matteos_power_spectrum
fatal_errors=T

[pipeline]
modules = consistency camb
values = ${Y3_CLUSTER_CPP_DIR}/cosmosis_tests/values/matteos_power_spectrum_values.ini
quiet=F
debug=T
timing=F

[consistency]
file = ${COSMOSIS_STANDARD_LIBRARY}/utility/consistency/consistency_interface.py

[camb]
file = ${COSMOSIS_STANDARD_LIBRARY}/boltzmann/camb/camb_interface.py
mode=power
lmax=2200
feedback=2
; from Cosmosis v1
; ; We want the power spectrum w/out neutrinos - version 2
; matter_power_lin_version = 2
; from Cosmosis v2
; ; We want the power spectrum w/out neutrinos - matter_power = "matter_de_power_lin"
power_spectra=delta_tot delta_nonu delta_cdm
; v1 
;; high_precision = T
;v2 not a thing. 
zmin = 0.00
zmax = 0.55
nz = 20
kmin = 1e-4
kmax = 50.0
nk = 1000

