[runtime]
sampler = test
root = ${COSMOSIS_SRC_DIR}

[test]
save_dir=matteos_power_spectrum
fatal_errors=T

[pipeline]
modules = consistency camb
values = /cosmosis/cosmosis-standard-library/y3_cluster_cpp/cosmosis_tests/matteos_power_spectrum_values.ini
quiet=F
debug=T
timing=F

[consistency]
file = cosmosis-standard-library/utility/consistency/consistency_interface.py

[camb]
file = cosmosis-standard-library/boltzmann/camb/camb.so
mode=all
lmax=2200
feedback=2
; We want the power spectrum w/out neutrinos - version 2
matter_power_lin_version = 2
zmin = 0.00
zmax = 0.55
nz = 20
kmin = 1e-4
kmax = 50.0
nk = 1000
