[runtime]
; The test sampler just runs a single parameter set
sampler = test
root = ${PWD}

[DEFAULT]

; If something goes wrong this will aid diagnosis
fatal_errors=T


[test]
save_dir = sdss_analysis_output

[output]
filename = randomized_starts_out_08_1000.txt
format = text
verbosity = 0

[emcee]
; The emcee sampler uses the concept of walkers, a collection
; ; ; of live points.  Sampling is done along lines that connect
; ; ; pairs of walkers.  The number of walkers must be at least
; ; ; 2*nparam + 1, but in general more than that usually works
; ; ; better.
walkers = 8
samples = 1000
; ; ; This is the interval at which convergence diagnostics
; ; ; are performed
nsteps = 10
;start_points = emcee_start_points.txt
random_start = T

; The pipeline section contains information
; that describes the sequence of calculations
; to be done and what we want out at the end
[pipeline]
; The list of modules to be run, in this order.
; The modules named here must appear as sections below
modules = consistency camb sigma_r mf_tinker sdss_analysis  sdss_analysis_test
; The file to get cosmological and nuisance parameters
; from.
values = ${Y3_CLUSTER_CPP_DIR}/cosmosis_tests/values/values_comp.ini
; Not used here, becuase we are not sampling
likelihoods = 
extra_output = 
quiet=T
debug=T
timing=T

; The consistency module translates between our chosen parameterization
; and any other that modules in the pipeline may want (e.g. camb)
[consistency]
file = ${COSMOSIS_STANDARD_LIBRARY}/utility/consistency/consistency_interface.py

[camb]
file = ${COSMOSIS_STANDARD_LIBRARY}/boltzmann/camb/camb_interface.py
mode=power
power_spectra=delta_tot delta_nonu
lmax=2500
feedback=0
zmin = 0.0
zmax = 0.55
nz = 100
kmin = 1e-4
kmax = 50.0
halofit_version = takahashi
nonlinear = both
nk = 182
; matter_power_lin_version = 3

; Halofit non-linear power
[halofit_takahashi]
file = ${COSMOSIS_STANDARD_LIBRARY}/boltzmann/halofit_takahashi/halofit_interface.so
nk = 182

[growth]
file = ${COSMOSIS_STANDARD_LIBRARY}/structure/growth_factor/interface.so
zmin = 0.0
;the convention for this module seems to be to include the last bin
zmax = 1.0
dz = 0.1

[sigma_r]
file = ${COSMOSIS_STANDARD_LIBRARY}/boltzmann/sigmar/sigmar.py
zmin = 0.0
zmax = 1.0
dz = 0.1
rmin = 1.0
rmax = 50.0
dr = 1.0
#matter_power = "matter_power_lin_cdm_baryon"
matter_power = "matter_de_power_lin"

[mf_tinker]
file = ${COSMOSIS_STANDARD_LIBRARY}/mass_function/mf_tinker/tinker_mf_module.so
; matter_power_lin_section_name = "matter_power_lin_cdm_baryon"
redshift_zero = 0
feedback=0
; matter_power_lin_version = 2

[sigma8_rescale]
file = ${COSMOSIS_STANDARD_LIBRARY}/utility/sample_sigma8/sigma8_rescale.py


[sdss_analysis]
file = ${Y3_CLUSTER_WORK_DIR}/src/modules/sdss_analysis/sdss_analysis.so
verbosity = 1
profile = T
lo_low = 20.0 27.9 37.6 50.3 69.3
lo_high = 27.9 37.6 50.3 69.3 140.0
lt_low = 5.0 5.0 10.0 20.0 30.0
lt_high = 50.0 80.0 100.0 120.0 159.0
zt_low = 0.05 0.05 0.05 0.05 0.1
zt_high = 0.4 0.4 0.4 0.4 0.40
lnm_low = 29.0 29.0 29.0 29.0 29.0
lnm_high = 38.0 38.0 38.0 38.0 38.0
zo_low = 0.1 0.1
zo_high = 0.3 0.3
eps_rel = 1.5e-3
eps_abs = 1.0e-11
max_eval = 1000000

[sdss_analysis_test]
file = ${Y3_CLUSTER_CPP_DIR}/cosmosis_tests/integrated_bin_test.py
