[runtime]
; The test sampler just runs a single parameter set
sampler = test
root = ${COSMOSIS_SRC_DIR}

[DEFAULT]
lo_bins = 20.0 27.9 37.6 50.3 69.3 140.0
zo_bins = 0.1 0.3
radii_bins = 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0

; If something goes wrong this will aid diagnosis
fatal_errors=T

[output]
filename = randomized_starts_out_08_1000.txt
format = text
verbosity = 0

[emcee]
; The emcee sampler uses the concept of walkers, a collection
; ; ; of live points.  Sampling is done along lines that connect
; ; ; pairs of walkers.  The number of walkers must be at least
; ; ; 2*nparam + 1, but in general more than that usually works
; ; ; better.
walkers = 8
samples = 1000
; ; ; This is the interval at which convergence diagnostics
; ; ; are performed
nsteps = 10
;start_points = emcee_start_points.txt
random_start = T

; The pipeline section contains information
; that describes the sequence of calculations
; to be done and what we want out at the end
[pipeline]
; The list of modules to be run, in this order.
; The modules named here must appear as sections below
modules = consistency camb sigma_r growth mf_tinker tinker_bias cluster_abundance cluster_mass_nc_like
; The file to get cosmological and nuisance parameters
; from.
values = /cosmosis/cosmosis-standard-library/y3_cluster_cpp/cosmosis_tests/values_comp.ini
; Not used here, becuase we are not sampling
likelihoods = like_cluster_mass_nc
extra_output = 
quiet=T
debug=F
timing=T

; The consistency module translates between our chosen parameterization
; and any other that modules in the pipeline may want (e.g. camb)
[consistency]
file = cosmosis-standard-library/utility/consistency/consistency_interface.py

[camb]
file = cosmosis-standard-library/boltzmann/camb/camb.so
mode=all
lmax=2500
feedback=0
zmin = 0.0
zmax = 0.55
nz = 100
kmin = 1e-4
kmax = 50.0
nk = 1000
matter_power_lin_version = 1

[growth]
file = cosmosis-standard-library/structure/growth_factor/interface.so
zmin = 0.0
;the convention for this module seems to be to include the last bin
zmax = 1.0
dz = 0.1

[sigma_r]
file = cosmosis-standard-library/boltzmann/sigmar/sigmar.py
zmin = 0.0
zmax = 1.0
dz = 0.1
rmin = 1.0
rmax = 50.0
dr = 1.0
matter_power = "matter_power_lin"

[mf_tinker]
file = cosmosis-standard-library/mass_function/mf_tinker/tinker_mf_module.so
redshift_zero = 0
feedback=0
matter_power_lin_version = 2

[sigma8_rescale]
file = cosmosis-standard-library/utility/sample_sigma8/sigma8_rescale.py

[tinker_bias]
file = cosmosis-standard-library/y3_cluster_cpp/tinker_bias/tinker_bias.py

[cluster_abundance]
file = cosmosis-standard-library/y3_cluster_cpp/src/libcluster_abundance.so

[cluster_mass_nc_like]
file = cosmosis-standard-library/cluster_mass_nc_like/likelihood.py
