[runtime]
; The test sampler just runs a single parameter set
sampler = test
root = ${COSMOSIS_SRC_DIR}

[test]
; These are the parameters for this sampler.
; In this case there is just one parameter
save_dir=cosmosis_test_output

; If something goes wrong this will aid diagnosis
fatal_errors=T

; The pipeline section contains information
; that describes the sequence of calculations
; to be done and what we want out at the end
[pipeline]
; The list of modules to be run, in this order.
; The modules named here must appear as sections below
modules = consistency camb gamma_t
; The file to get cosmological and nuisance parameters
; from.
values = /cosmosis/cosmosis-standard-library/y3_cluster_cpp/cosmosis_tests/values.ini
; Not used here, becuase we are not sampling
likelihoods = 
extra_output = 
quiet=F
debug=T
timing=F

; The consistency module translates between our chosen parameterization
; and any other that modules in the pipeline may want (e.g. camb)
[consistency]
file = cosmosis-standard-library/utility/consistency/consistency_interface.py

[camb]
file = cosmosis-standard-library/boltzmann/camb/camb.so
mode=all
lmax=2500
feedback=2

#[camb]
#file = cosmosis-standard-library/boltzmann/camb/camb.so
#mode=all
#lmax=2600          ;max ell to use for cmb calculation
#feedback=2         ;amount of output to print
#accuracy_boost=1.1 ;CAMB accuracy boost parameter
#high_acc_default=true ;high accuracy is required w/ Planck data
#kmax = 100.0       ;max k - matter power spectrum
#zmin = 0.0	       ;min value to save P(k,z)
#zmax = 1.0         ;max value to save P(k,z) 
#nz = 20            ;number of z values to save P(k,z) 
#do_tensors=false   ;include tensor modes
#do_lensing=true    ;lensing is required w/ Planck data
#high_ell_template=cosmosis-standard-library/boltzmann/camb/camb_Jan15/HighLExtrapTemplate_lenspotentialCls.dat

[gamma_t]
file = cosmosis-standard-library/y3_cluster_cpp/src/libexample_module.so
## MOR
#mor_A = 1.0
#mor_B = 1.0
#mor_C = 1.0
#mor_sigma = 1.0
#mor_alpha = 1.0
## LO_LC
#lo_lc_alpha = 1.0
#lo_lc_a = 1.0
#lo_lc_b = 1.0
#lo_lc_R_lambda = 1.0
## LC_LT
#lc_lt_tau = 1.0
#lc_lt_mu = 1.0
#lc_lt_sigma = 1.0
#lc_lt_fmsk = 1.0
#lc_lt_fprj = 1.0
## ZO_ZT
#zo_zt_sigma = 1.0
## ROFFSET
#roffset_tau = 1.0
## HMF
#hmf_s = 1.0
#hmf_q = 1.0
