[cosmological_parameters]
h0 = 0.6774
omega_m = 0.3089
omega_b = 0.0486
omega_k = 0.0
tau = 0.091
;tau = 0.078
n_s = 0.9667
log1e10As = 3.90460746e+00
sigma8_input = 0.8159
;sigma8_input = 0.9
w = -1.0
wa = 0.0
;massless_nu=3.046
massless_nu=0
massive_nu=0
omega_nu=0.00

; These parameters can affect everything but are not required - 
; if they are not found in this file they take the sensible
; default values shown here
#omega_k = 0.0
#w = -1.0
#wa = 0.0
[cluster_mass_profile]
concentration = 5.0

[cluster_abundance]
fcen = 1.0
# MOR
mor_A = 137252859112.81984
mor_B = 2645961929488.942
mor_alpha = 6.91589257e-01
mor_sigma = 1.29339555e-01
# LO_LC
lo_lc_alpha = 1.66
lo_lc_a = 0.26
lo_lc_b = 1.43
lo_lc_R_lambda = 1.0
# LC_LT
lc_lt_tau = 1.0
lc_lt_mu = 1.0
lc_lt_sigma = 1.0
lc_lt_fmsk = 1.0
lc_lt_fprj = 1.0
# ZO_ZT
zo_zt_sigma = 0.005
# PZSOURCE
pzsource_zbin = 0.4
pzsource_sigma = 0.2
# ROFFSET
roffset_tau = 0.2
# HMF
;hmf_s = 4.50732047e-02
;hmf_q = 1.01958078e+00
hmf_s = 0.0
hmf_q = 1.0

