#!/usr/bin/env bash

#rm -rf cmake_install.cmake CTestTestfile.cmake Testing Makefile CMakeFiles
rm -f Makefile test/Makefile src/Makefile src/utils/Makefile src/models/Makefile src/modules/Makefile
rm -f CTestTestfile.cmake test/CTestTestfile.cmake src/CTestTestfile.cmake src/utils/CTestTestfile.cmake src/models/CTestTestfile.cmake src/modules/CTestTestfile.cmake
rm -f cmake_install.cmake test/cmake_install.cmake src/cmake_install.cmake src/utils/cmake_install.cmake src/models/cmake_install.cmake src/modules/cmake_install.cmake
rm -rf CMakeFiles test/CMakeFiles  src/CMakeFiles src/utils/CMakeFiles src/models/CMakeFiles src/modules/CMakeFiles
rm -f CMakeCache.txt
rm -f build.ninja .ninja_deps .ninja_log
find . -type f -name '*.dylib' -delete
find . -type f -name '*.so' -delete
find . -type f -name '*.pyc' -delete
rm -rf Testing/
rm -f test/*_test
rm -f deltasigma/test/Sigma_mm_2halo.out
rm -f deltasigma/test/Sigma_nfwonly.out
rm -f deltasigma/test/bias.out
rm -f deltasigma/test/xi_mm_2halo.out
rm -f deltasigma/test/xi_nfwonly.out
rm -rf masses_test_output/
rm -rf sdss_analysis_output/
