[runtime]
; The test sampler just runs a single parameter set
sampler = test
root = ${COSMOSIS_SRC_DIR}

[test]
; These are the parameters for this sampler.
; In this case there is just one parameter
save_dir = OUTPUT

; If something goes wrong this will aid diagnosis
fatal_errors=T

; The pipeline section contains information
; that describes the sequence of calculations
; to be done and what we want out at the end
[pipeline]
; The list of modules to be run, in this order.
; The modules named here must appear as sections below
modules = consistency camb halofit_takahashi sigma_r tinker_bias xihm
; The file to get cosmological and nuisance parameters
; from.
values = values.ini
; Not used here, becuase we are not sampling
likelihoods = 
extra_output = 
quiet=F
debug=T
timing=T

; The consistency module translates between our chosen parameterization
; and any other that modules in the pipeline may want (e.g. camb)
[consistency]
file = cosmosis-standard-library/utility/consistency/consistency_interface.py

; A module!  Camb, set to a mode where it does
; background evolution, CMB, and matter power
[camb]
file = cosmosis-standard-library/boltzmann/camb/camb.so
mode=all
zmin=0.1
zmax=0.3
nz=100
lmax=2600          ;max ell to use for cmb calculation
feedback=2         ;amount of output to print

; Halofit non-linear power
[halofit_takahashi]
file = cosmosis-standard-library/boltzmann/halofit_takahashi/halofit_interface.so
kmin = 1e-5
kmax = 200.0
nk = 200

[sigma_r]
file = cosmosis-standard-library/boltzmann/sigmar/sigmar.py
zmin = 0
zmax = 1.0
dz = 0.05
rmin = 0.1
rmax = 200.0
dr = 1.0
matter_power = "matter_power_lin"

[tinker_bias]
file = cosmosis-standard-library/y3_cluster_cpp/tinker_bias/tinker_bias.py

[xihm]
file = cosmosis-standard-library/y3_cluster_cpp/xi_hm/src/libxihm.so

; distance in the sky, in Mpc/h
R_perp_min = 0.001 
R_perp_max = 100.0
R_perp_bins = 300

; Radii of xi_hm, in Mpc/h
Radii_min = 0.01
Radii_max = 100
Radii_bins = 300

; cluster mass, in Msun/h
M_min = 5E11
M_max = 1E17
M_bins = 300
z_min = 0.0
z_max = 1.0
z_bins = 10
concentration = 5.0
