[cosmological_parameters]
h0 = 0.6726       ;H0 (km/s/Mpc)/100.0km/s/Mpc 
omega_m = 0.3141  ;density fraction for matter today
omega_b = 0.04    ;density fraction for baryons today
omega_k = 0.0     ;spatial curvature

;neutrinos
mnu = 0.06
nnu = 3.046
num_massive_neutrinos = 1


;helium 
yhe = 0.245341  ;helium mass fraction

;reionization
tau = 0.08      ;reionization optical depth

;inflation Parameters
n_s = 0.96      ;scalar spectral index
A_s = 2.1e-9    ;scalar spectrum primordial amplitude
k_s = 0.05      ;Power spectrum pivot scale 
n_run = 0.0     ;running of scalar spectrum 
r_t = 0.2       ;tensor to scalar ratio
n_t = 0.0       ;tensor spectral index 

;dark energy equation of state
w = -1.0   ;equation of state of dark energy
wa = 0.0   ;equation of state of dark energy (redshift dependency)

# the old values file, for Cosmosis 1.4,  had these settings:
;massless_nu=0.046
;massive_nu=3
# That corresponds to an inverted hierarchy of degenerate neutrino masses (see:p3 of https://cosmologist.info/notes/CAMB.pdf)
# for Cosmosis 2.0, we're using 
; neutrino_hierarchy = inverted
; num_massive_neutrinos = 3
# but these will be in the [camb] section of masses_test.ini


; These parameters can affect everything but are not required - 
; if they are not found in this file they take the sensible
; default values shown here
#omega_k = 0.0
#w = -1.0
#wa = 0.0

[cluster_abundance]
fcen = 1.0
# MOR
mor_A = 137252859112.81984
mor_B = 2645961929488.942
mor_alpha = 6.91589257e-01
mor_sigma = 1.29339555e-01
# LO_LC
lo_lc_alpha = 1.66
lo_lc_a = 0.26
lo_lc_b = 1.43
lo_lc_R_lambda = 1.0
# LC_LT
lc_lt_tau = 1.0
lc_lt_mu = 1.0
lc_lt_sigma = 1.0
lc_lt_fmsk = 1.0
lc_lt_fprj = 1.0
# ZO_ZT
zo_zt_sigma = 0.005
# PZSOURCE
pzsource_zbin = 0.4
pzsource_sigma = 0.2
# ROFFSET
roffset_tau = 0.2
# HMF
hmf_s = 4.50732047e-02
hmf_q = 1.01958078e+00
# Integration ranges:
lnM_min = 29.0
lnM_max = 38.0
lt_min = 2.0
lt_max = 140.0
lc_min = 2.0
lc_max = 140.0
zo_min = 0.05 
;zo_min this one should not be necessary
zo_max = 0.35
;zo_max this one should not be necessary
zt_min = 0.05
zt_max = 0.35
R_min = 0.0
R_max = 3.0
A_min = -0.01
A_max = 0.01
theta_min = 0.0
theta_max = 6.28318530718

