[runtime]
; The test sampler just runs a single parameter set
sampler = test
root = ${COSMOSIS_SRC_DIR}

[DEFAULT]
; If something goes wrong this will aid diagnosis
fatal_errors=T
grid_file = ${COSMOSIS_SRC_DIR}/cosmosis-standard-library/y3_cluster_cpp/cosmosis_tests/sptxy1/inputs/mock36_noxi/mock_richest36_noxi.cat
lamobs_low = 104.47920757346424
nclusters = 36

[test]
save_dir = output

[output]
filename = randomized_starts_out_08_1000.txt
format = text
verbosity = 1

[pipeline]
; The list of modules to be run, in this order.
modules = consistency camb mf_tinker mass_conversion ztrue_integration abundance_integral selection_integral richest_clusters_likelihood

; The file to get cosmological and nuisance parameters from
values = ${COSMOSIS_SRC_DIR}/cosmosis-standard-library/y3_cluster_cpp/cosmosis_tests/sptxy1/inputs/mock36_noxi/values.ini

; Not used here, becuase we are not sampling
likelihoods = 
extra_output = 
quiet=T
debug=T
timing=T

; The consistency module translates between our chosen parameterization
; and any other that modules in the pipeline may want (e.g. camb)
[consistency]
file = cosmosis-standard-library/utility/consistency/consistency_interface.py

[camb]
file = cosmosis-standard-library/boltzmann/camb/camb.so
mode=all
lmax=2500
feedback=0
zmin = 0.0
zmax = 1.0
nz = 100
kmin = 1e-4
kmax = 50.0
nk = 1000
matter_power_lin_version = 3

[mf_tinker]
file = cosmosis-standard-library/mass_function/mf_tinker/tinker_mf_module.so
matter_power_lin_section_name = "matter_power_lin_cdm_baryon"
redshift_zero = 0
feedback=0
matter_power_lin_version = 2


[mass_conversion]
file = cosmosis-standard-library/y3_cluster_cpp/src/modules/mass_conversion/cosmosis_m200m_to_m500c.py
cM_model = fixedc200c
c200c = 4.0


[ztrue_integration]
file = cosmosis-standard-library/y3_cluster_cpp/src/modules/AbundanceIntegralZtrue_DESxSPTModule.so
Nsigma_ztrue = 5.
eps_rel = 1.0e-5
eps_abs = 1.0e-50
max_eval = 10000000


[abundance_integral]
file = cosmosis-standard-library/y3_cluster_cpp/src/modules/AbundanceIntegralMLamtrue_DESxSPTModule.so

; Integration bounds
lamtrue_bounds = 60. 300.
lnM200m_bounds = 28. 38.

; Default integration params
eps_rel = 1.5e-3
eps_abs = 1.0e-50
max_eval = 10000000
use_cartesian_product = False


[selection_integral]
file = cosmosis-standard-library/y3_cluster_cpp/src/modules/SelectionIntegralDESxSPTModule.so

; Bounds fixed by survey
zobs_min = 0.2
zobs_max = 0.65

; Integration bounds over infinity
lamobs_high = 500.

lamtrue_low = 30.
lamtrue_high = 400.

lnM200m_low = 27.
lnM200m_high = 39.

ztrue_low = 0.10
ztrue_high = 0.75

; Default integration parameters
eps_rel = 1.5e-3
eps_abs = 1.0e-50
max_eval = 10000000
use_cartesian_product = False

[richest_clusters_likelihood]
file = cosmosis-standard-library/y3_cluster_cpp/src/modules/CompleteDESxSPTLikelihoodModule.py
