[cosmological_parameters]
h0 = 0.6336569
omega_m = 0.34056257882
omega_b = 0.05649329977
omega_k = 0.0
tau = 0.08
n_s = 0.975589
log1e10As = 3.092918
w = -1.0
wa = 0.0
massless_nu=0
massive_nu=3.046
omega_nu=0.0

; These parameters can affect everything but are not required - 
; if they are not found in this file they take the sensible
; default values shown here
#omega_k = 0.0
#w = -1.0
#wa = 0.0
[cluster_mass_profile]
concentration=5

[abundance_integral]
Mmin = 1.0e11
M1 = 1.4e12
alpha = 0.75
epsilon = 0.0
sig0lam = 0.32
Asz = 4.08
Bsz = 1.65
Csz = 0.64
sig0zeta = 0.20
r = 0.0
zplam = 0.45
lnMpsz = 33.
zpsz = 0.6

[cluster_abundance]
hmf_s = 0.00
hmf_q = 1.00

