[runtime]
; The test sampler just runs a single parameter set
sampler = test
root = ${COSMOSIS_SRC_DIR}

[DEFAULT]
; If something goes wrong this will aid diagnosis
fatal_errors=T

[test]
save_dir = output

[output]
filename = randomized_starts_out_08_1000.txt
format = text
verbosity = 1

[pipeline]
; The list of modules to be run, in this order.
modules = consistency camb mf_tinker mass_conversion abundance_integral
; The file to get cosmological and nuisance parameters
; from.
values = ${COSMOSIS_SRC_DIR}/cosmosis-standard-library/y3_cluster_cpp/cosmosis_tests/sptxy1/values_y1_with_sptsz.ini
; Not used here, becuase we are not sampling
likelihoods = 
extra_output = 
quiet=T
debug=T
timing=T

; The consistency module translates between our chosen parameterization
; and any other that modules in the pipeline may want (e.g. camb)
[consistency]
file = cosmosis-standard-library/utility/consistency/consistency_interface.py

[camb]
file = cosmosis-standard-library/boltzmann/camb/camb.so
mode=all
lmax=2500
feedback=0
zmin = 0.0
zmax = 1.0
nz = 100
kmin = 1e-4
kmax = 50.0
nk = 1000
matter_power_lin_version = 3

[mf_tinker]
file = cosmosis-standard-library/mass_function/mf_tinker/tinker_mf_module.so
matter_power_lin_section_name = "matter_power_lin_cdm_baryon"
redshift_zero = 0
feedback=0
matter_power_lin_version = 2

[mass_conversion]
file = cosmosis-standard-library/y3_cluster_cpp/src/modules/sptxdes/mass_conversion/cosmosis_m200m_to_m500c.py
cM_model = fixedc200c
c200c = 4.0

[abundance_integral]
file = cosmosis-standard-library/y3_cluster_cpp/src/modules/sptxdes_abundance_integral.so

ztrue_low = 0.2 0.2
ztrue_high = 0.3 0.3
; ztrue_low = 0.15 0.15
; ztrue_high = 0.75 0.75

lnM200m_low = 28. 28.
lnM200m_high = 39. 39.
; lnM200m_high = 37. 37.

lamtrue_low = 60. 60.
lamtrue_high = 300. 300.
; lamtrue_low = 60. 60.
; lamtrue_high = 300. 300.

; zeta_low = 2.0 2.0
; zeta_high = 100. 100.
zeta_low = 5.0 5.0
zeta_high = 17. 17.

lamobs = 175. 175.
xi = 12. 12.
zobs = 0.23 0.23
gamma_field = 1.1 1.1
eps_rel = 1.5e-3
eps_abs = 1.0e-50
max_eval = 10000000
