#!/usr/bin/env python
# -*- coding: utf-8 -*-

from setuptools import setup, Extension
from Cython.Build import cythonize
import glob
import os


def camel_case(name):
    return ''.join([s.capitalize() for s in name.split('_')])

# This warning is for generated files - it is not about this script (setup.py)
warning = """
# ---- # ---- DO NOT EDIT ---- # ---- #
# This file is auto-generated by the setup.py script,
# and any changes you make WILL be overwritten.
"""

model_import_template = """
cdef extern from "{file}" namespace "y3_cluster":
    cdef cppclass {typename}:
        pass
"""

models_list_template = """
models = [{}]
"""

with open('cluster_abundance_skel.pyx') as f:
    interface_text = f.read().format(warning=warning)
with open('integrand_interface_skel.pyx') as f:
    integrand_impl_text = f.read()
with open('cluster_abundance_skel.pxd') as f:
    definition_text = f.read()


typenames = []
typedefs = []
integrand_impls = []
for model in glob.glob('../*_models.hh'):
    print('processing model:', model)
    # Do some string processing
    fname = os.path.basename(model)
    ctypename = camel_case(fname.split('.')[0])
    typenames.append('Integrand' + ctypename)

    # Populate templates
    typedef = model_import_template.format(file=fname,
                                           typename=ctypename)
    typedefs.append(typedef)

    igrnd_impl = integrand_impl_text.format(typename=ctypename)
    integrand_impls.append(igrnd_impl)

# Add definitions
definition_text += '\n\n' + '\n\n'.join(typedefs)

with open('cluster_abundance.pxd', mode='w') as f:
    f.write(definition_text)

# Add interface
interface_text += '\n\n' + '\n\n'.join(integrand_impls)
interface_text += models_list_template.format(', '.join(typenames))

with open('cluster_abundance.pyx', mode='w') as f:
    f.write(interface_text)

# Now, all the code is generated, and we can start the real build system.
# TODO: get these from CMake
include_dirs = [os.path.join(os.path.dirname(__file__), '..'),
                '/cosmosis/cubacpp/',
                '/cosmosis/cubacpp/cubacpp/']

if __name__ == '__main__':
    setup(
        name='cluster_abundance',
        ext_modules=cythonize(
            Extension('cluster_abundance',
                      sources=['cluster_abundance.pyx'],
                      language='c++',
                      extra_objects=['../liblc_lt.a', '../libinterp.a'],
                      # TODO: get these from CMake
                      extra_compile_args=['-O3', '-Wall', '-std=c++17'],
                      include_dirs=include_dirs,
                      libraries=['cosmosis', 'gsl', 'cuba', 'gslcblas'],
                      library_dirs=['/cosmosis/cosmosis/datablock/'],
                      ),
            annotate=True
            )
        )
