[cosmological_parameters]
h0 = 0.6336569
omega_m = 0.34056257882
omega_b = 0.05649329977
omega_k = 0.0
tau = 0.08
log1e10As = 3.092918
sigma8_input = 0.8159
n_s = 0.975589
w = -1.0
wa = 0.0

; Neutrino physics
; Sum of neutrino masses (in eV); Omega_nu is calculated approximately from this.
mnu = 0.0
; as the default is 1, it seems likely one can approximate 3 as 1 for case of mass(n_1) >> mass(n_2, or n_3)
num_massive_neutrinos = 3
; N_eff, the effective relativistic degrees of freedom
nnu = 3.046 
neutrino_hierarchy = 1
