[runtime]
; The test sampler just runs a single parameter set
sampler = test
root = ${COSMOSIS_SRC_DIR}

[DEFAULT]

; If something goes wrong this will aid diagnosis
fatal_errors=T

# Variables of integration.
lo_low = 20.0
lo_high = 30.0
lc_low = 5.0
lc_high = 50.0
lt_low = 5.0
lt_high = 50.0
zt_low = 0.15
zt_high = 0.75
lnm_low = 29.0
lnm_high = 38.0
rmis_low = 0.0
rmis_high = 2.0
theta_low = 0.0
theta_high = 6.28318530718

# Variables defining grid for integrands
zo_low = 0.2
zo_high = 0.35
#radii = 0.01 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0 2.0 3.0 4.0 5.0 6.0 7.0 8.0 9.0 10.0 20.0 30.0
radii = 2.0

# Integration algorithm configuration
eps_rel = 0.002
eps_abs = 1.0e-12
max_eval = 500_000_000
use_cartesian_product = True
algorithm = cuhre

[test]
save_dir = cuda_test_out

[output]
filename = cuda_test.txt
format = text
verbosity = 0

[emcee]
; The emcee sampler uses the concept of walkers, a collection
; ; ; of live points.  Sampling is done along lines that connect
; ; ; pairs of walkers.  The number of walkers must be at least
; ; ; 2*nparam + 1, but in general more than that usually works
; ; ; better.
walkers = 8
samples = 1000
; ; ; This is the interval at which convergence diagnostics
; ; ; are performed
nsteps = 10
;start_points = emcee_start_points.txt
random_start = T

; The pipeline section contains information
; that describes the sequence of calculations
; to be done and what we want out at the end
[pipeline]
; The list of modules to be run, in this order.
; The modules named here must appear as sections below
modules = consistency camb halofit_takahashi growth mf_tinker deltasigma SigmaCentY1MortScalarIntegrand SigmaMiscentY1CUDAIntegrand NCCentY1MortScalarIntegrand NCMiscentY1MortScalarIntegrand 
; The file to get cosmological and nuisance parameters
; from.
values = ${Y3_CLUSTER_CPP_DIR}/y1_rerun/values_comp_y1.ini
; Not used here, becuase we are not sampling
likelihoods = 
extra_output = 
quiet=T
debug=T
timing=T

; The consistency module translates between our chosen parameterization
; and any other that modules in the pipeline may want (e.g. camb)
[consistency]
file = cosmosis-standard-library/utility/consistency/consistency_interface.py

[camb]
file = cosmosis-standard-library/boltzmann/camb/camb.so
mode=all
lmax=2500
feedback=0
zmin = 0.0
zmax = 0.55
nz = 100
kmin = 1e-4
kmax = 50.0
nk = 1000
matter_power_lin_version = 3

; Halofit non-linear power
[halofit_takahashi]
file = cosmosis-standard-library/boltzmann/halofit_takahashi/halofit_interface.so
nk = 182

[growth]
file = cosmosis-standard-library/structure/growth_factor/interface.so
zmin = 0.0
;the convention for this module seems to be to include the last bin
zmax = 1.0
dz = 0.1

[sigma_r]
file = cosmosis-standard-library/boltzmann/sigmar/sigmar.py
zmin = 0.0
zmax = 1.0
dz = 0.1
rmin = 1.0
rmax = 50.0
dr = 1.0
matter_power = "matter_power_lin_cdm_baryon"

[mf_tinker]
file = cosmosis-standard-library/mass_function/mf_tinker/tinker_mf_module.so
matter_power_lin_section_name = "matter_power_lin_cdm_baryon"
redshift_zero = 0
feedback=0
matter_power_lin_version = 2


[sigma8_rescale]
file = cosmosis-standard-library/utility/sample_sigma8/sigma8_rescale.py

[deltasigma]
file = ${Y3_CLUSTER_CPP_DIR}/src/modules/deltasigma/deltasigma.py

; distance in the sky, in Mpc/h
R_perp_min = 0.01
R_perp_max = 250
R_perp_bins = 1000
; ;
; ; ; Radii of xi_hm, in Mpc/h
Radii_min = 0.01
Radii_max = 1000
Radii_bins = 1000
; ;
; ; ; cluster mass, in Msun/h
M_min = 1E12
M_max = 1E16
M_bins = 100
;

[SigmaMiscentY1CUDAIntegrand]
file = ${Y3_CLUSTER_WORK_DIR}/src/modules/cuda/SigmaMiscentY1MortCUDAScalarIntegrand.so
verbosity = 1
profile = T

[SigmaCentY1MortScalarIntegrand]
file = ${Y3_CLUSTER_WORK_DIR}/src/modules/sigma_mort_y1/SigmaCentY1MortScalarIntegrand.so
verbosity = 1
profile = T

[NCMiscentY1MortScalarIntegrand]
file = ${Y3_CLUSTER_WORK_DIR}/src/modules/mass_mort_y1/NCMiscentY1MortScalarIntegrand.so
verbosity = 1
profile = T 

[NCCentY1MortScalarIntegrand]
file = ${Y3_CLUSTER_CPP_DIR}/src/modules/mass_mort_y1/NCCentY1MortScalarIntegrand.so
verbosity = 1

[SigmaMort_Like]
file = ${Y3_CLUSTER_WORK_DIR}/y1_rerun/SigmaMort_likelihood.py
algorithm = "frog"
