[runtime]
sampler = test
root = ${COSMOSIS_SRC_DIR}

[DEFAULT]
fatal_errors=T

# Variables of integration.
# Note:
#    sigma cent uses:    lo,     zt, lnM
#    sigma miscent uses: lo, lc, zt, lnM, rmis, theta
#    NC cent uses:       lo,     zt, lnM
#    NC miscent uses:    lo, lc, zt, lnM, rmis

lo_low     = 20.0          30.0          45.0         60.0
lo_high    = 30.0          45.0          60.0        190.0

lc_low     =  5.0           5.0          10.0          20.0
lc_high    = 50.0          80.0         100.0         190.0

zt_low     =  0.15          0.15          0.15          0.15
zt_high    =  0.75          0.75          0.75          0.75

lnm_low    = 29.0          29.0          29.0          29.0
lnm_high   = 38.0          38.0          38.0          38.0

rmis_low   =  0.0           0.0           0.0           0.0
rmis_high  =  2.0           2.0           2.0           2.0

theta_low  =  0.0           0.0           0.0           0.0
theta_high =  6.28318530718 6.28318530718 6.28318530718 6.28318530718

# Variables defining grid for integrands
zo_low  = 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2
zo_high = 0.35 0.35 0.35 0.35 0.35 0.35 0.35 0.35 0.35 0.35 0.35 0.35 0.35 0.35 0.35 0.35 0.35 0.35 0.35 0.35 0.35 0.35 0.35
radii   = 0.01 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0 2.0 3.0 4.0 5.0 6.0 7.0 8.0 9.0 10.0 20.0 30.0 35.0


# Integration algorithm configuration
eps_rel = 1e-3
eps_abs = 1.0e-12
use_cartesian_product = True

[test]
save_dir = mcubes_test_out

[pipeline]
modules = consistency camb halofit_takahashi growth mf_tinker deltasigma SigmaCentY1CUDAIntegrand SigmaMiscentY1CUDAIntegrand NCCentY1CUDAIntegrand NCMiscentY1CUDAIntegrand
values = ${Y3_CLUSTER_CPP_DIR}/y1_rerun/values_comp_y1.ini
# values = ${Y3_CLUSTER_CPP_DIR}/y1_rerun/values_y1_analysis.ini
quiet = T
debug = T
timing = T

[consistency]
file = cosmosis-standard-library/utility/consistency/consistency_interface.py

[camb]
file = cosmosis-standard-library/boltzmann/camb/camb.so
mode=all
lmax=2500
feedback=0
zmin = 0.0
zmax = 0.55
nz = 100
kmin = 1e-4
kmax = 50.0
nk = 1000
matter_power_lin_version = 3

[halofit_takahashi]
file = cosmosis-standard-library/boltzmann/halofit_takahashi/halofit_interface.so
nk = 182

[growth]
file = cosmosis-standard-library/structure/growth_factor/interface.so
zmin = 0.0
zmax = 1.0
dz = 0.1

[mf_tinker]
file = cosmosis-standard-library/mass_function/mf_tinker/tinker_mf_module.so
redshift_zero = 0
feedback=0
matter_power_lin_version = 2

[deltasigma]
file = ${Y3_CLUSTER_CPP_DIR}/src/modules/deltasigma/deltasigma.py
R_perp_min = 0.01
R_perp_max = 250
R_perp_bins = 1000
Radii_min = 0.01
Radii_max = 1000
Radii_bins = 1000
M_min = 1E12
M_max = 1E16
M_bins = 100

[SigmaCentY1CUDAIntegrand]
file = ${Y3_CLUSTER_WORK_DIR}/src/modules/sigma_mort_y1/SigmaCentY1MortCUDAScalarIntegrand.so
algorithm = mcubes
max_eval = 1e5
timing_file = "sigma_cent.txt"

[SigmaMiscentY1CUDAIntegrand]
file = ${Y3_CLUSTER_WORK_DIR}/src/modules/sigma_mort_y1/SigmaMiscentY1MortCUDAScalarIntegrand.so
algorithm = mcubes
max_eval = 1e5
timing_file = "sigma_miscent.txt"

[NCCentY1CUDAIntegrand]
file = ${Y3_CLUSTER_WORK_DIR}/src/modules/mass_mort_y1/NCCentY1MortCUDAScalarIntegrand.so
algorithm = mcubes
max_eval = 1e5
timing_file = "nc_cent.txt"

[NCMiscentY1CUDAIntegrand]
file = ${Y3_CLUSTER_WORK_DIR}/src/modules/mass_mort_y1/NCMiscentY1MortCUDAScalarIntegrand.so
algorithm = mcubes
max_eval = 1e5
timing_file = "nc_miscent.txt"
