[cosmological_parameters]
h0 = 0.6336569
#omega_m = 0.34056257882
omega_m = 0.2
omega_b = 0.05649329977
omega_k = 0.0
tau = 0.08
n_s = 0.975589
log1e10As = 3.092918
w = -1.0
wa = 0.0
massless_nu=0
massive_nu=3.046
omega_nu=0.0

; These parameters can affect everything but are not required - 
; if they are not found in this file they take the sensible
; default values shown here
#omega_k = 0.0
#w = -1.0
#wa = 0.0
[cluster_mass_profile]
concentration=5
[photoz]
delta_z=0.0

[cluster_abundance]
fcen = 0.7
; MOR
#mor_A = 90124651837.9
#mor_B = 2291711130000.0
mor_A = 2.0e-13
mor_B = 1.0
;mor_alpha = 6.98949129e-01
mor_alpha = 0.01
mor_sigma = 0.5
;1.46305833e-01
;mor_epsilon = -2.02589520e-01 
mor_epsilon = 0.0
z_mor_pivot = 0.45
mor_skew = 0.1
# LO_LC
lo_lc_alpha = 1.66
lo_lc_a = 0.26
lo_lc_b = 1.43
lo_lc_R_lambda = 1.0
# LC_LT
lc_lt_tau = 1.0
lc_lt_mu = 1.0
lc_lt_sigma = 1.0
lc_lt_fmsk = 1.0
lc_lt_fprj = 1.0
# ZO_ZT
zo_zt_sigma = 0.005
# ROFFSET
roffset_tau = 0.2
# HMF
hmf_s = 0.00
hmf_q = 1.00

