[cosmological_parameters]
h0 = 0.6726       ;H0 (km/s/Mpc)/100.0km/s/Mpc 
omega_m = 0.267   ;density fraction for matter today
omega_b = 0.045   ;density fraction for baryons today
omega_k = 0.0     ;spatial curvature
tau = 0.08
log1e10As = 3.97
sigma8_input = 0.91
n_s = 0.963
w = -1.0
wa = 0.0
; Neutrino physics
; Sum of neutrino masses (in eV); Omega_nu is calculated approximately from this.
mnu = 0.0
; as the default is 1, it seems likely one can approximate 3 as 1 for case of mass(n_1) >> mass(n_2, or n_3)
num_massive_neutrinos = 3
; N_eff, the effective relativistic degrees of freedom
nnu = 3.046 
neutrino_hierarchy = 1
