[runtime]
; use either the test or list sampler.
; sampler = emcee
; sampler = test
sampler = apriori
root = ${COSMOSIS_SRC_DIR}


[emcee]
; The emcee sampler uses the concept of walkers, a collection
; ; ; of live points.  Sampling is done along lines that connect
; ; ; pairs of walkers.  The number of walkers must be at least
; ; ; 2*nparam + 1, but in general more than that usually works
; ; ; better.
walkers = 60
samples = 5000
; ; ; This is the interval at which convergence diagnostics
; ; ; are performed
nsteps = 1
;start_points = emcee_start_points.txt
random_start = T

; The pipeline section contains information
; that describes the sequence of calculations
; to be done and what we want out at the end

[apriori]
save_dir = /global/common/software/des/paterno/y3_cluster_cpp/y3_buzzard/output
save = datablock

[DEFAULT]
; If something goes wrong this will aid diagnosis
fatal_errors =  true

[output]
filename = simple_chain
format = text
verbosity = debug

; The pipeline section contains information
; that describes the sequence of calculations
; to be done and what we want out at the end
[pipeline]
modules = dummy
quiet=True
debug=True
timing=True
values = ${Y3_CLUSTER_CPP_DIR}/y3_buzzard/dummy_values.ini

[dummy]
file = ${Y3_CLUSTER_WORK_DIR}/src/modules/sigma_buzzard_y3/dummy.so
; Integration algorithm configuration
eps_rel = 5e-3
eps_abs = 1.0e-12

# the following refers to how to handle the integration volumes
algorithm = pagani
max_eval = 1e8
use_cartesian_product = True
# Integration volumes
x_low    =  0.0  0.0  0.0  0.0  0.0        
x_high   = 10.0 10.0 10.0 10.0 10.0 

y_low    =  0.0  0.0  0.0  0.0  0.0        
y_high   = 20.0 20.0 20.0 20.0 20.0 
# Grid for integration
a = 1.0 2.0 3.0 4.0 5.0 6.0 7.0 8.0 9.0 10.0
do_cartesian_product_of_bins = False
