[runtime]
; use either the test or list sampler.
; sampler = zeus
sampler = test
;sampler = apriori
root = ${COSMOSIS_SRC_DIR}

[test]
save_dir = output
[apriori]
save_dir = output

[zeus]
save_dir = output
walkers = 30
samples = 3
nsteps = 5
;nsteps = 50

[DEFAULT]
; If something goes wrong this will aid diagnosis
fatal_errors =  true

[output]
filename = test.out
format = text
verbosity = debug
; The pipeline section contains information
; that describes the sequence of calculations
; to be done and what we want out at the end
[pipeline]
modules = consistency mf_tinker numberCounts

values = ${Y3_CLUSTER_CPP_DIR}/y1_park/values_y1_park.ini
;
; We can not yet run this likelihood, because the predictions from our
; integrands have diffent shapes. We have to update the likelihood to
; understand that NC predictions do not have radius dependence.
;
; likelihoods = SigmaMort_Like
quiet=True
debug=True
timing=True

; The consistency module translates between our chosen parameterization
; and any other that modules in the pipeline may want (e.g. camb)
[consistency]
file = ${COSMOSIS_STANDARD_LIBRARY}/utility/consistency/consistency_interface.py

[mf_tinker]
file = ${COSMOSIS_STANDARD_LIBRARY}/mass_function/mf_tinker/tinker_mf_module.so
redshift_zero = 0
feedback=0
matter_power_lin_version = 2

[numberCounts]
file = ${Y3_CLUSTER_WORK_DIR}src/modules/scaling_relations/scaling_relation_integrand.cu
; Integration configuration
eps_rel = 5e-3
eps_abs = 1.0e-12

# the following refers to how to handle the integration volumes
use_cartesian_product = True
algorithm = pagani
max_eval = 1e8
# Integration volumes
x1_low     =  20.0            30.0            45.0            60.0 
x1_high    =  30.0            45.0            60.0           190.0

# 0-infinity
#lt_low     =   1.0              1.0            1.0              1.0
#lt_high    = 500.0            500.0          500.0            500.0
# not 0-infinity
x2_low     =   5.0             5.0            10.0            20.0
x2_high    =  50.0            80.0           100.0           190.0

# 0- nfinity 10^8 to 10^17 =  18 to 39
#lnm_low    =  18.0            18.0            18.0            18.0
#lnm_high   =  39.0            39.0            39.0            39.0
# not 0-infinity
lnm_low    =  29.0            29.0            29.0            29.0
lnm_high   =  38.0            38.0            38.0            38.0

# the following refers to the grid points
filename='spt-lambda-bocquet-y1.txt'

; # the following refers to the grid points
; do_cartesian_product_of_bins = False
; # Grid for integration
; ;zo_bottom    = 0.2  0.35  0.5
; ;zo_bin_width = 0.15  0.15  0.15
; zo_low = 0.2 0.35 0.5
; zo_high = 0.35 0.5 0.65
; radii = 0.01 0.01 0.01 
; radius = 0.01 

# To do: Write a likelihood function
; [likelihood]
; file = ${Y3_CLUSTER_WORK_DIR}/src/modules/
