[runtime]
; use either the test or list sampler.
; sampler = metropolis
sampler = test
; sampler = apriori
; sampler = polychord
; root = ${COSMOSIS_SRC_DIR}

[test]
save_dir = /global/homes/j/jesteves/des_data/chains/pagani/

[polychord]
base_dir = chain_checkpoints
polychord_outfile_root = poly_y1_mock
live_points = 100
;; number of repeats should be ~3*number of parameters
num_repeats = 15
resume = T
feedback = 3
boost_posterior = 5.0

[apriori]
nsample = 100
save_dir = ./
save = ./

[DEFAULT]
; If something goes wrong this will aid diagnosis
fatal_errors =  true

[output]
filename = chain1d
format = text
verbosity = debug

; The pipeline section contains information
; that describes the sequence of calculations
; to be done and what we want out at the end
[pipeline]
modules = consistency camb mf_tinker haloModel sigmaCritInv numberCountsCard gammaCentPark opSelBias likelihoods
# buildShear buildSigmaCritInv like_proto
; likelihoods = likelihoods
values = ./values_y1.ini
; priors = ./prior_y1.ini
quiet=False
debug=False
timing=True

; The consistency module translates between our chosen parameterization
; and any other that modules in the pipeline may want (e.g. camb)
[consistency]
file = ${COSMOSIS_STANDARD_LIBRARY}/utility/consistency/consistency_interface.py

[camb]
file = ${COSMOSIS_STANDARD_LIBRARY}/boltzmann/camb/camb_interface.py
halofit_version = takahashi
feedback=0
kmax = 50.0
kmin = 5e-3
lmax = 2500
mode=all
power_spectra=delta_tot delta_nonu
nk = 128
nonlinear = both
nz = 50
; zmax must be higher than the highest integration range
zmax = 1.0
; If the infinities in the distance outputs disturb you, use the following
; zmin = 0.0001
; If you are using sigma8_rescale, though, zmin must = 0.
zmin = 0.0

[mf_tinker]
file = ${COSMOSIS_STANDARD_LIBRARY}/mass_function/mf_tinker/tinker_mf_module.so
redshift_zero = 0
feedback=0
matter_power_lin_version = 2

[sigma8_rescale]
file = ${COSMOSIS_STANDARD_LIBRARY}/utility/sample_sigma8/sigma8_rescale.py


[haloModel]
file = ${Y3_CLUSTER_CPP_DIR}/y3_buzzard/haloModelCosmosis.py
; file = ${Y3_CLUSTER_CPP_DIR}/y3_buzzard/buildXi.py
; Radii of Sigma_1,2,  in Mpc/h comoving
R_perp_min = 0.05
R_perp_max = 10.
R_perp_bins = 128
; Radii of Wp_hh/nfw, in Mpc/h comoving
Radii_min = 1.0
Radii_max = 35.
Radii_bins = 128
; cluster mass, in Msun/h
M_min = 1e12
M_max = 1e16
M_bins = 100
; cluster photo-z error
; for now is simply the peculiar velocity
sigma_photoz = 0.01 

[sigmaCritInv]
file = ${Y3_CLUSTER_CPP_DIR}/y3_buzzard/buildSigmaCritInv.py
beta_lut = ${Y3_CLUSTER_CPP_DIR}/data/beta_sigCrit_lut_mock_buzzard_zl.npz
; BE CAREFUL, the shear is actually Delta Sigma
; IF is_delta_sigma = True
is_delta_sigma = False

[grabLoLt]
file = ${Y3_CLUSTER_CPP_DIR}/y3_buzzard/grab_intLoLt.py
fname_z = int_lc_lt_des_t_zt_bins.txt
fname_l = int_lc_lt_des_t_lt_bins.txt
fname_bin = int_lc_lt_des_t_lbd_bin{}.txt

[numberCountsCard]
file = ${Y3_CLUSTER_WORK_DIR}/src/modules/gt_card_gpu/numberCountsCard.so
; Integration algorithm configuration
eps_rel = 1e-2
eps_abs = 1.0e-12

# the following refers to how to handle the integration volumes
use_cartesian_product = True
algorithm = pagani
max_eval = 1e8

# Integration volumes
lnLo_low  = 2.996    3.401    3.807    4.094
lnLo_high = 3.401    3.807    4.094    5.298

lnLt_low  = 2.049    2.485    2.923    3.033
lnLt_high = 3.638    3.97    4.263    5.182

zt_low  = 0.15    0.15    0.15    0.15
zt_high = 0.75    0.75    0.75    0.75

lnm_low  = 28.0    28.0    28.0    28.0
lnm_high = 37.0    37.0    37.0    37.0

# the following refers to the grid points
do_cartesian_product_of_bins = False
# Grid for integration
zo_low   = 0.2 0.35 0.5
zo_high  = 0.35 0.5 0.65

[gammaCentPark]
file = ${Y3_CLUSTER_WORK_DIR}/src/modules/gt_card_gpu/avgCentCard.so
; Integration algorithm configuration
eps_rel = 1e-2
eps_abs = 1.0e-12
# the following refers to how to handle the integration volumes
use_cartesian_product = True
algorithm = pagani
;algorithm = mcubes
max_eval = 1e8

# Integration volumes
lnLo_low  = 2.996    3.401    3.807    4.094
lnLo_high = 3.401    3.807    4.094    5.298

lnLt_low  = 2.049    2.485    2.923    3.033
lnLt_high = 3.638    3.97    4.263    5.182

zt_low  = 0.15    0.15    0.15    0.15
zt_high = 0.75    0.75    0.75    0.75

lnm_low  = 28.0    28.0    28.0    28.0
lnm_high = 37.0    37.0    37.0    37.0

# Grid for integration
zo_low  = 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.35 0.35 0.35 0.35 0.35 0.35 0.35 0.35 0.35 0.35 0.35 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5
zo_high = 0.35 0.35 0.35 0.35 0.35 0.35 0.35 0.35 0.35 0.35 0.35 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.65 0.65 0.65 0.65 0.65 0.65 0.65 0.65 0.65 0.65 0.65
radii  = 0.001 0.05 0.083 0.139 0.232 0.387 0.646 1.077 1.797 2.997 5.0 0.001 0.05 0.083 0.139 0.232 0.387 0.646 1.077 1.797 2.997 5.0 0.001 0.05 0.083 0.139 0.232 0.387 0.646 1.077 1.797 2.997 5.0
radius = 0.001 0.05 0.083 0.139 0.232 0.387 0.646 1.077 1.797 2.997 5.0

# the following refers to the grid points
do_cartesian_product_of_bins = False

[opSelBias]
file = ${Y3_CLUSTER_CPP_DIR}/y1_park/op_el_bias_nfw_efffective.py
zo_low  = 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.35 0.35 0.35 0.35 0.35 0.35 0.35 0.35 0.35 0.35 0.35 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5
zo_high = 0.35 0.35 0.35 0.35 0.35 0.35 0.35 0.35 0.35 0.35 0.35 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.65 0.65 0.65 0.65 0.65 0.65 0.65 0.65 0.65 0.65 0.65
radii  = 0.001 0.05 0.083 0.139 0.232 0.387 0.646 1.077 1.797 2.997 5.0 0.001 0.05 0.083 0.139 0.232 0.387 0.646 1.077 1.797 2.997 5.0 0.001 0.05 0.083 0.139 0.232 0.387 0.646 1.077 1.797 2.997 5.0
lbdbins = 20 30 45 60 200

[likelihoods]
file = ${Y3_CLUSTER_CPP_DIR}/y3_buzzard/likelihood_m.py
filename = /global/cfs/cdirs/des/jesteves/data/buzzard/v1.9.8/y3_rm/dataVec_mock_Aug10th2023.npz